=== workivate/onboarding-file-formats/xml/schema/full_import.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="https://lifeworks.com/onboarding/xml/v1/Users"
           targetNamespace="https://lifeworks.com/onboarding/xml/v1/Users">
    <xs:simpleType name="countryCode">
        <xs:restriction base="xs:string">
            <xs:enumeration value="AF"/>
            <xs:enumeration value="AX"/>
            <xs:enumeration value="AL"/>
            <xs:enumeration value="DZ"/>
            <xs:enumeration value="AD"/>
            <xs:enumeration value="AO"/>
            <xs:enumeration value="AI"/>
            <xs:enumeration value="AQ"/>
            <xs:enumeration value="AG"/>
            <xs:enumeration value="AR"/>
            <xs:enumeration value="AS"/>
            <xs:enumeration value="AM"/>
            <xs:enumeration value="AW"/>
            <xs:enumeration value="AU"/>
            <xs:enumeration value="AT"/>
            <xs:enumeration value="AZ"/>
            <xs:enumeration value="BS"/>
            <xs:enumeration value="BH"/>
            <xs:enumeration value="BD"/>
            <xs:enumeration value="BB"/>
            <xs:enumeration value="BY"/>
            <xs:enumeration value="BE"/>
            <xs:enumeration value="BZ"/>
            <xs:enumeration value="BJ"/>
            <xs:enumeration value="BM"/>
            <xs:enumeration value="BT"/>
            <xs:enumeration value="BO"/>
            <xs:enumeration value="BQ"/>
            <xs:enumeration value="BA"/>
            <xs:enumeration value="BW"/>
            <xs:enumeration value="BV"/>
            <xs:enumeration value="BR"/>
            <xs:enumeration value="IO"/>
            <xs:enumeration value="BN"/>
            <xs:enumeration value="BG"/>
            <xs:enumeration value="BF"/>
            <xs:enumeration value="BI"/>
            <xs:enumeration value="KH"/>
            <xs:enumeration value="CM"/>
            <xs:enumeration value="CA"/>
            <xs:enumeration value="CV"/>
            <xs:enumeration value="KY"/>
            <xs:enumeration value="CF"/>
            <xs:enumeration value="TD"/>
            <xs:enumeration value="CL"/>
            <xs:enumeration value="CN"/>
            <xs:enumeration value="CX"/>
            <xs:enumeration value="CC"/>
            <xs:enumeration value="CO"/>
            <xs:enumeration value="KM"/>
            <xs:enumeration value="CG"/>
            <xs:enumeration value="CD"/>
            <xs:enumeration value="CK"/>
            <xs:enumeration value="CR"/>
            <xs:enumeration value="CI"/>
            <xs:enumeration value="HR"/>
            <xs:enumeration value="CU"/>
            <xs:enumeration value="CW"/>
            <xs:enumeration value="CY"/>
            <xs:enumeration value="CZ"/>
            <xs:enumeration value="DK"/>
            <xs:enumeration value="DO"/>
            <xs:enumeration value="DJ"/>
            <xs:enumeration value="DM"/>
            <xs:enumeration value="EC"/>
            <xs:enumeration value="EG"/>
            <xs:enumeration value="SV"/>
            <xs:enumeration value="GQ"/>
            <xs:enumeration value="ER"/>
            <xs:enumeration value="EE"/>
            <xs:enumeration value="ET"/>
            <xs:enumeration value="FK"/>
            <xs:enumeration value="FO"/>
            <xs:enumeration value="FJ"/>
            <xs:enumeration value="FI"/>
            <xs:enumeration value="FR"/>
            <xs:enumeration value="GF"/>
            <xs:enumeration value="PF"/>
            <xs:enumeration value="TF"/>
            <xs:enumeration value="GA"/>
            <xs:enumeration value="GM"/>
            <xs:enumeration value="GE"/>
            <xs:enumeration value="DE"/>
            <xs:enumeration value="GH"/>
            <xs:enumeration value="GI"/>
            <xs:enumeration value="GR"/>
            <xs:enumeration value="GL"/>
            <xs:enumeration value="GD"/>
            <xs:enumeration value="GP"/>
            <xs:enumeration value="GU"/>
            <xs:enumeration value="GT"/>
            <xs:enumeration value="GG"/>
            <xs:enumeration value="GN"/>
            <xs:enumeration value="GW"/>
            <xs:enumeration value="GY"/>
            <xs:enumeration value="HT"/>
            <xs:enumeration value="HM"/>
            <xs:enumeration value="VA"/>
            <xs:enumeration value="HN"/>
            <xs:enumeration value="HK"/>
            <xs:enumeration value="HU"/>
            <xs:enumeration value="IS"/>
            <xs:enumeration value="IN"/>
            <xs:enumeration value="ID"/>
            <xs:enumeration value="IR"/>
            <xs:enumeration value="IQ"/>
            <xs:enumeration value="IE"/>
            <xs:enumeration value="IM"/>
            <xs:enumeration value="IL"/>
            <xs:enumeration value="IT"/>
            <xs:enumeration value="JM"/>
            <xs:enumeration value="JP"/>
            <xs:enumeration value="JE"/>
            <xs:enumeration value="JO"/>
            <xs:enumeration value="KZ"/>
            <xs:enumeration value="KE"/>
            <xs:enumeration value="KI"/>
            <xs:enumeration value="KP"/>
            <xs:enumeration value="KR"/>
            <xs:enumeration value="KW"/>
            <xs:enumeration value="KG"/>
            <xs:enumeration value="LA"/>
            <xs:enumeration value="LV"/>
            <xs:enumeration value="LB"/>
            <xs:enumeration value="LS"/>
            <xs:enumeration value="LR"/>
            <xs:enumeration value="LY"/>
            <xs:enumeration value="LI"/>
            <xs:enumeration value="LT"/>
            <xs:enumeration value="LU"/>
            <xs:enumeration value="MO"/>
            <xs:enumeration value="MK"/>
            <xs:enumeration value="MG"/>
            <xs:enumeration value="MW"/>
            <xs:enumeration value="MY"/>
            <xs:enumeration value="MV"/>
            <xs:enumeration value="ML"/>
            <xs:enumeration value="MT"/>
            <xs:enumeration value="MH"/>
            <xs:enumeration value="MQ"/>
            <xs:enumeration value="MR"/>
            <xs:enumeration value="MU"/>
            <xs:enumeration value="YT"/>
            <xs:enumeration value="MX"/>
            <xs:enumeration value="FM"/>
            <xs:enumeration value="MD"/>
            <xs:enumeration value="MC"/>
            <xs:enumeration value="MN"/>
            <xs:enumeration value="ME"/>
            <xs:enumeration value="MS"/>
            <xs:enumeration value="MA"/>
            <xs:enumeration value="MZ"/>
            <xs:enumeration value="MM"/>
            <xs:enumeration value="NA"/>
            <xs:enumeration value="NR"/>
            <xs:enumeration value="NP"/>
            <xs:enumeration value="NL"/>
            <xs:enumeration value="NC"/>
            <xs:enumeration value="NZ"/>
            <xs:enumeration value="NI"/>
            <xs:enumeration value="NE"/>
            <xs:enumeration value="NG"/>
            <xs:enumeration value="NU"/>
            <xs:enumeration value="NF"/>
            <xs:enumeration value="MP"/>
            <xs:enumeration value="NO"/>
            <xs:enumeration value="OM"/>
            <xs:enumeration value="PK"/>
            <xs:enumeration value="PW"/>
            <xs:enumeration value="PS"/>
            <xs:enumeration value="PA"/>
            <xs:enumeration value="PG"/>
            <xs:enumeration value="PY"/>
            <xs:enumeration value="PE"/>
            <xs:enumeration value="PH"/>
            <xs:enumeration value="PN"/>
            <xs:enumeration value="PL"/>
            <xs:enumeration value="PT"/>
            <xs:enumeration value="PR"/>
            <xs:enumeration value="QA"/>
            <xs:enumeration value="RE"/>
            <xs:enumeration value="RO"/>
            <xs:enumeration value="RU"/>
            <xs:enumeration value="RW"/>
            <xs:enumeration value="BL"/>
            <xs:enumeration value="SH"/>
            <xs:enumeration value="KN"/>
            <xs:enumeration value="LC"/>
            <xs:enumeration value="MF"/>
            <xs:enumeration value="PM"/>
            <xs:enumeration value="VC"/>
            <xs:enumeration value="WS"/>
            <xs:enumeration value="SM"/>
            <xs:enumeration value="ST"/>
            <xs:enumeration value="SA"/>
            <xs:enumeration value="SN"/>
            <xs:enumeration value="RS"/>
            <xs:enumeration value="SC"/>
            <xs:enumeration value="SL"/>
            <xs:enumeration value="SG"/>
            <xs:enumeration value="SX"/>
            <xs:enumeration value="SK"/>
            <xs:enumeration value="SI"/>
            <xs:enumeration value="SB"/>
            <xs:enumeration value="SO"/>
            <xs:enumeration value="ZA"/>
            <xs:enumeration value="GS"/>
            <xs:enumeration value="SS"/>
            <xs:enumeration value="ES"/>
            <xs:enumeration value="LK"/>
            <xs:enumeration value="SD"/>
            <xs:enumeration value="SR"/>
            <xs:enumeration value="SJ"/>
            <xs:enumeration value="SZ"/>
            <xs:enumeration value="SE"/>
            <xs:enumeration value="CH"/>
            <xs:enumeration value="SY"/>
            <xs:enumeration value="TW"/>
            <xs:enumeration value="TJ"/>
            <xs:enumeration value="TZ"/>
            <xs:enumeration value="TH"/>
            <xs:enumeration value="TL"/>
            <xs:enumeration value="TG"/>
            <xs:enumeration value="TK"/>
            <xs:enumeration value="TO"/>
            <xs:enumeration value="TT"/>
            <xs:enumeration value="TN"/>
            <xs:enumeration value="TR"/>
            <xs:enumeration value="TM"/>
            <xs:enumeration value="TC"/>
            <xs:enumeration value="TV"/>
            <xs:enumeration value="UG"/>
            <xs:enumeration value="UA"/>
            <xs:enumeration value="AE"/>
            <xs:enumeration value="GB"/>
            <xs:enumeration value="US"/>
            <xs:enumeration value="UM"/>
            <xs:enumeration value="UY"/>
            <xs:enumeration value="UZ"/>
            <xs:enumeration value="VU"/>
            <xs:enumeration value="VE"/>
            <xs:enumeration value="VN"/>
            <xs:enumeration value="VG"/>
            <xs:enumeration value="VI"/>
            <xs:enumeration value="WF"/>
            <xs:enumeration value="EH"/>
            <xs:enumeration value="YE"/>
            <xs:enumeration value="ZM"/>
            <xs:enumeration value="ZW"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="locale">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z]{2,2}_[A-Z]{2,2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="dateYMD">
        <xs:restriction base="xs:string">
            <xs:pattern value="(1[8-9][0-9]{2}|2[0-9]{3})[^0-9]+(10|11|12|0?[1-9])[^0-9]+(0?[1-9]|[12][0-9]|3[01])"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="emailRFC5322">
        <xs:restriction base="xs:string">
            <xs:pattern
                    value='(([^&lt;&gt;()\[\].,;:\s@"]+(\.[^&lt;&gt;()\[\].,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([\w\-0-9]+\.)+[a-zA-Z]{2,}))'/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="group">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
            <xs:maxLength value="255" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="gender">
        <xs:restriction base="xs:string">
            <xs:enumeration value="male"/>
            <xs:enumeration value="female"/>
            <xs:enumeration value="other"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="userElement">
        <xs:sequence>

            <xs:element name="company_id" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="company_name" type="xs:string" minOccurs="1" maxOccurs="1"/>

            <xs:element name="employee_id" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="email" type="emailRFC5322" minOccurs="0" maxOccurs="1"/>

            <xs:element name="activation_date" type="dateYMD" minOccurs="0" maxOccurs="1"/>
            <xs:element name="termination_date" type="dateYMD" minOccurs="0" maxOccurs="1"/>
            
            <xs:element name="first_name" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="last_name" type="xs:string" minOccurs="0" maxOccurs="1"/>

            <xs:element name="country_code" type="countryCode" minOccurs="0" maxOccurs="1"/>
            <xs:element name="locale" type="locale" minOccurs="0" maxOccurs="1"/>

            <xs:element name="gender" type="gender" minOccurs="0" maxOccurs="1"/>
            <xs:element name="job_title" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="group" type="group" minOccurs="0" maxOccurs="1"/>
            <xs:element name="phone_mobile" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="phone_work" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="birthday" type="dateYMD" minOccurs="0" maxOccurs="1"/>
            <xs:element name="work_start" type="dateYMD" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="email" type="emailRFC5322"/>
        <xs:attribute name="employee_id" type="xs:string" />
    </xs:complexType>
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" type="userElement" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== workivate/onboarding-file-formats/xml/examples/full_import.xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:users xmlns:xs="https://lifeworks.com/onboarding/xml/v1/Users"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://lifeworks.com/onboarding/xml/v1/Users ../schema/full_import.xsd">
    <user>
        <company_id>C12345</company_id>
        <company_name>Name of the company</company_name>
        <employee_id>1</employee_id>
        <email>me@example.com</email>
        <activation_date>2018-11-20</activation_date>
        <first_name>Jane</first_name>
        <last_name>Doe</last_name>
        <country_code>GB</country_code>
        <locale>en_GB</locale>
        <gender>female</gender>
        <job_title>Director</job_title>
        <phone_mobile>+48747883322</phone_mobile>
        <phone_work>+48747883322</phone_work>
        <birthday>1919-09-30</birthday>
        <work_start>2011-12-19</work_start>
    </user>
    <user>
        <company_id>C12345</company_id>
        <company_name>Name of the company</company_name>
        <employee_id>2</employee_id>
        <email>you@example.com</email>
        <activation_date>2018-11-20</activation_date>
        <termination_date>2020-11-20</termination_date>
        <first_name>John</first_name>
        <last_name>Doe</last_name>
        <country_code>US</country_code>
        <gender>male</gender>
        <job_title>Director</job_title>
        <phone_mobile>+48747883322</phone_mobile>
        <phone_work>+48747883322</phone_work>
        <birthday>1919-09-30</birthday>
        <work_start>2011-12-19</work_start>
    </user>
    <user>
        <company_id>C12345</company_id>
        <company_name>Name of the company</company_name>
        <employee_id>3</employee_id>
        <email>someone@example.com</email>
        <activation_date>2018-11-20</activation_date>
        <first_name>János</first_name>
        <last_name>Kovács</last_name>
        <country_code>HU</country_code>
        <gender>other</gender>
        <group>IT</group>
        <phone_mobile/>
        <phone_work/>
        <birthday>1919-09-30</birthday>
        <work_start>2011-12-19</work_start>
    </user>
    <user>
        <company_id>C12345</company_id>
        <company_name>Name of the company</company_name>
        <email>email@fallback.test</email>
        <activation_date>2018-11-20</activation_date>
        <first_name>  </first_name>
        <last_name/>
        <gender/>
        <job_title/>
        <phone_mobile>   </phone_mobile>
        <phone_work/>
        <birthday>   </birthday>
        <work_start/>
    </user>
</xs:users>
